{{- if .Values.report.kibana.enable }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: grafana-reports-cronjob
spec:
  schedule: "59 11 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: init-kibana
            image: busybox:1.32
            command: [sh, -c] 
            args:
              - | 
                echo -e "Checking for the availability of Kibana server"
                while ! nc -z axonect-monetiser-kibana.default.svc.cluster.local 5601
                do 
                  sleep 1
                  printf "-" 
                done 
                echo -e "  >>  Kibana server has started"
          containers:
          - name: report
            image: gcr.io/cia-rnd-195110/grafana-reports:2.0.0
            command: [bash, -c] 
            env:
              - name: GRAFANA
                value: "{{ .Values.report.grafana.enable }}"
              - name: KIBANA
                value: "{{ .Values.report.kibana.enable }}"
            args:
              - |
                mkdir -p /reports/scripts
                cp -r /scripts/* /reports/scripts/
                cd /reports/scripts/
                ls -l
                cd kibana
                chmod +x dalily-reports-kibana.sh
                /bin/bash dalily-reports-kibana.sh
                sleep 5
            volumeMounts:
            - name: kibana-reports-configmap
              mountPath: /scripts/kibana
          restartPolicy: Never
          volumes:
          - name: kibana-reports-configmap
            configMap:
              name: {{ .Release.Name }}-kibana-reports-configmap
{{- end }}