apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-datetime-printer
  namespace : {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datetime-printer
  template:
    metadata:
      labels:
        app: datetime-printer
    spec:
      containers:
      - name: datetime-printer
        image: busybox
        command: ["/bin/sh", "-c", "while true; do date; sleep 1; done"]
