apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-server-ingress
  namespace : {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{.Values.server.ingress.hostname }}-{{ .Values.global.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-nginx-service
                port:
                  number: 8080