apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service
  namespace : {{ .Release.Namespace }}
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
