apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-grafana-report
spec:
  initContainers:
  - name: init-grafana
    image: busybox:1.32
    command: [sh, -c] 
    args:
      - | 
        echo -e "Checking for the availability of Grafana server"
        while ! nc -z axonect-monetiser-grafana 80
        do 
          sleep 1
          printf "-" 
        done 
        echo -e "  >>  Grafana server has started"
  containers:
  - name: grafana-report
    image: gcr.io/cia-rnd-195110/grafana-reports:2.0.0
    command: [bash, -c] 
    args:
      - |
        cp /scripts/* /grafana-reports/scripts/
        cd /grafana-reports/scripts
        ls -l
        chmod +x dalily-reports.sh
        /bin/bash dalily-reports.sh
        
        echo "Grafana dailly reports generation Success!!!"
    volumeMounts:
    - name: grafana-reports-configmap
      mountPath: /scripts
  volumes:
  - name: grafana-reports-configmap
    configMap:
      name: {{ .Release.Name }}-grafana-reports-configmap