{
 "title": "AXP Gateway Traffic Dashboard Pdf",
 "tags": [ "axp" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ingress",
    "label": "ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{namespace=\"ingress-nginx\"},ingress)"
    }
   }
  ]
 },
 "panels": [
  { "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 0 },
   "options": {
    "content": "<p style=\"font-size:500%;fond-weight:bold;color:#E3E4FA;>\"> Gateway Hourly Report </p>"
   }
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 } },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Request Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase (axp_gw_request_total{job=\"kubernetes-pods\"}[$__range])) + sum (increase (axp_gw_failed_total{job=\"kubernetes-pods\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffics success rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(increase (axp_gw_request_total{job=\"kubernetes-pods\"}[$__range])) \n/\n(sum(increase (axp_gw_request_total{job=\"kubernetes-pods\"}[$__range])) + sum (increase (axp_gw_failed_total{job=\"kubernetes-pods\"}[$__range])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(axp_gw_request_total{job=\"kubernetes-pods\"}[60s]))",
     "legendFormat": "Total trafic"
    }
   ]
  },
  {
   "title": "Gateway Traffic By API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (api_name) (rate(axp_gw_request_total{job=\"kubernetes-pods\"}[60s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Traffic By Application",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (application_name) (rate(axp_gw_request_total{job=\"kubernetes-pods\"}[60s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Request Count [200]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(axp_gw_response_total{job=\"kubernetes-pods\", status_code=~\"2..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Request Failed Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(axp_gw_failed_total{job=\"kubernetes-pods\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Traffic By API",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (api_name) (increase(axp_gw_request_total{job=\"kubernetes-pods\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Traffic By Application",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (application_name) (increase(axp_gw_request_total{job=\"kubernetes-pods\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Traffic By API (Top 10)",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (api_name) (increase(axp_gw_request_total{job=\"kubernetes-pods\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (api_name) (increase (axp_gw_failed_total{job=\"kubernetes-pods\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Traffic with Success and Failed ",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 13 },
   "targets": [
    {
     "expr": "sum by (api_name) (increase(axp_gw_response_total{job=\"kubernetes-pods\", status_code=~\"2..\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (api_name) (increase(axp_gw_failed_total{job=\"kubernetes-pods\", status_code=~\"404\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (api_name) (increase (axp_gw_failed_total{job=\"kubernetes-pods\", status_code=~\"401\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (api_name) (increase (axp_gw_failed_total{job=\"kubernetes-pods\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (api_name) (increase (axp_gw_request_total{job=\"kubernetes-pods\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (le,status) (increase (nginx_ingress_controller_request_duration_seconds_bucket{job=\"ingress-nginx-controller-metrics\", ingress=~\"axonect-monetiser-am-gateway-ingress\", le=\"0.25\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (le,status) (increase (nginx_ingress_controller_request_duration_seconds_bucket{job=\"ingress-nginx-controller-metrics\", ingress=~\"axonect-monetiser-am-gateway-ingress\", le=\"0.5\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency < 0.25",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 21 },
   "targets": [
    {
     "expr": "sum by (le,status) (increase (nginx_ingress_controller_request_duration_seconds_bucket{job=\"ingress-nginx-controller-metrics\", ingress=~\"axonect-monetiser-am-gateway-ingress\", le=\"0.25\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (increase(axp_gw_request_latency_sum{job=\"kubernetes-pods\"}[1m])\n  / clamp_min(increase(axp_gw_request_latency_count{job=\"kubernetes-pods\"}[1m]), 1)) by (api_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(\n  (\n    sum (increase(axp_gw_request_latency_sum{job=\"kubernetes-pods\"}[1m])\n    / clamp_min(increase(axp_gw_request_latency_count{job=\"kubernetes-pods\"}[1m]), 1)) by (api_name)\n  )[$__range:]\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "min_over_time(\n  (\n    (sum (increase(axp_gw_request_latency_sum{job=\"kubernetes-pods\"}[1m])\n    / clamp_min(increase(axp_gw_request_latency_count{job=\"kubernetes-pods\"}[1m]), 1)) by (api_name)) > 0\n  )[$__range:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (increase(axp_gw_backend_latency_sum{job=\"kubernetes-pods\"}[1m])\n  / clamp_min(increase(axp_gw_backend_latency_count{job=\"kubernetes-pods\"}[1m]), 1)) by (api_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(\n  (\n    sum (increase(axp_gw_backend_latency_sum{job=\"kubernetes-pods\"}[1m])\n    / clamp_min(increase(axp_gw_backend_latency_count{job=\"kubernetes-pods\"}[1m]), 1)) by (api_name)\n  )[$__range:]\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "min_over_time(\n  (\n    (sum (increase(axp_gw_backend_latency_sum{job=\"kubernetes-pods\"}[1m])\n    / clamp_min(increase(axp_gw_backend_latency_count{job=\"kubernetes-pods\"}[1m]), 1)) by (api_name)) > 0\n  )[$__range:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (increase(axp_gw_response_latency_sum{job=\"kubernetes-pods\"}[1m])\n  / clamp_min(increase(axp_gw_response_latency_count{job=\"kubernetes-pods\"}[1m]), 1)) by (api_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(\n  (\n    sum (increase(axp_gw_response_latency_sum{job=\"kubernetes-pods\"}[1m])\n    / clamp_min(increase(axp_gw_response_latency_count{job=\"kubernetes-pods\"}[1m]), 1)) by (api_name)\n  )[$__range:]\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "min_over_time(\n  (\n    (sum (increase(axp_gw_response_latency_sum{job=\"kubernetes-pods\"}[1m])\n    / clamp_min(increase(axp_gw_response_latency_count{job=\"kubernetes-pods\"}[1m]), 1)) by (api_name)) > 0\n  )[$__range:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Error Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(axp_gw_failed_total{job=\"kubernetes-pods\"}[60s]))",
     "legendFormat": "Total Traffic"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max (increase(axp_gw_request_latency_sum{job=\"kubernetes-pods\"}[1m])\n  / clamp_min(increase(axp_gw_request_latency_count{job=\"kubernetes-pods\"}[1m]), 1)) by (api_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max (increase(axp_gw_backend_latency_sum{job=\"kubernetes-pods\"}[1m])\n  / clamp_min(increase(axp_gw_backend_latency_count{job=\"kubernetes-pods\"}[1m]), 1)) by (api_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max (increase(axp_gw_response_latency_sum{job=\"kubernetes-pods\"}[1m])\n  / clamp_min(increase(axp_gw_response_latency_count{job=\"kubernetes-pods\"}[1m]), 1)) by (api_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backend Latency > 100ms",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "count_over_time(\n  (\n    increase(axp_gw_backend_latency_sum{job=\"kubernetes-pods\"}[1m]) \n    / clamp_min(increase(axp_gw_backend_latency_count{job=\"kubernetes-pods\"}[1m]), 1)\n  > 100\n  )[1h:]\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}