FROM gcr.io/cia-rnd-195110/axp-dep:axonect-2.2.31

RUN ls -l Axonect-Monetiser/repository/components/dropins

COPY --chown=axpuser:axp . /home/axpuser/

RUN ls -l Axonect-Monetiser/repository/components/dropins
# /Axonect-Monetiser/repository/components/dropins

# wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.17/mysql-connector-java-8.0.17.jar