apiVersion: v1
kind: Pod
metadata:
  name: grafana-report
  namespace: gateway-common
spec:
  containers:
  - name: grafana-report
    image: maven:3.8.8-amazoncorretto-17
    command: [bash, -c] 
    args:
      - |
        yum install -y git
        echo sleeping
        sleep 360000
