externalConfigDir: "modified"

grafanaReport:
  smtp:
    host: "smtp.gmail.com"
    port: "587"
    username: "pavithresupprtfw1@gmail.com"
    password: "alzfjobodjlnehfu"
    sender: "pavithresupprtfw1@gmail.com"
    receiver: 
      - "pavithresupprtfw1@gmail.com"
      - "pavithrerathnayake@gmail.com"
      - "desmond.allon@gmail.com"

  grafana:
    username: "admin"
    password: "cxgKpmUPfhzbYUX6zxV2"
    dashboards: 
      - "http://axonect-monetiser-grafana.default/d/3X-EcUm4k/axp-gateway-traffic-dashboard-pdf?orgId=1&from=now-12h&to=now"
      - "http://axonect-monetiser-grafana.default/d/3X-EcUm4ka/axp-gateway-traffic-dashboard-pdfa?orgId=1&from=now-12h&to=now"
      - "http://axonect-monetiser-grafana.default/d/3X-EcUm4kb/axp-gateway-traffic-dashboard-pdfb?orgId=1&from=now-12h&to=now"