{{- if .Values.deployments.nfs.enable -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nfs-ingress
  namespace : {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{.Values.nfs.ingress.hostname }}-{{ .Values.global.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-nfs-server
                port:
                  number: 2049
{{- end }}